org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment


mod_id=wrench_plus
mod_name=Wrench Plus
mod_license=MIT
mod_version=1.0
mod_group_id=com.kaleblangley
mod_authors=Kaleb Langley
mod_description=

enableAccessTransformers=false

create_version = 6.0.6-150
ponder_version = 1.0.80
flywheel_version = 1.0.4
registrate_version = MC1.20-1.3.3
